version: '3'
services:
  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - 7545:8545
    networks:
      backend:
        ipv4_address: 172.15.0.3
    entrypoint: ["node", "/app/ganache-core.docker.cli.js", "--db", "./ganache_cache","--networkId","0x2324","--gasLimit","10000000000","--gasPrice","1","---hardfork","istanbul","--mnemonic","${GANACHE_MNEMONIC}"]

    volumes:
       - ${BLOCKCHAIN_VOLUME}:/app/ganache_cache

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.15.0.1/24